services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: traveltrip_db
      POSTGRES_USER: traveltrip_user # 修正：改為和 DATABASE_URL 一致的用戶名
      POSTGRES_PASSWORD: ${DB_PASS} # 從環境變數讀取
    volumes:
      - traveltrip_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U traveltrip_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - DEBUG=${DEBUG}
    # 新增：指定要執行的指令
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db_backup:
    image: prodrigestivill/postgres-backup-local:15
    restart: always
    volumes:
      - ./backups:/backups
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

volumes:
  traveltrip_postgres_data:
