# Generated by Django 4.2.7 on 2026-02-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='trips/'),
        ),
    ]
