# Generated by Django 4.2.7 on 2026-02-22 14:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': '旅遊行程', 'verbose_name_plural': '旅遊行程'},
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 22, 14, 43, 1, 231690, tzinfo=datetime.timezone.utc), verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='featured',
            field=models.BooleanField(default=False, help_text='精選行程會優先顯示', verbose_name='精選行程'),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True, help_text='未啟用的行程不會顯示在前台', verbose_name='啟用狀態'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='可用座位數'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.CharField(max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(max_length=100, verbose_name='國家'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(verbose_name='行程描述'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='行程天數'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(verbose_name='結束日期'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='trips/', verbose_name='行程圖片'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='keywords',
            field=models.CharField(blank=True, help_text='用於搜尋和推薦的關鍵字，以逗號分隔', max_length=200, verbose_name='關鍵字'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(max_length=100, verbose_name='地點'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=200, verbose_name='行程名稱'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='價格'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(verbose_name='開始日期'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['country', 'city'], name='trips_trip_country_e1b481_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['-created_at'], name='trips_trip_created_44654c_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_active', '-featured'], name='trips_trip_is_acti_9b2ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['start_date', 'end_date'], name='trips_trip_start_d_290e5d_idx'),
        ),
    ]
